### ISSUE TITLE
Docker-compose로 WCOW와 LCOW 동시 사용하기

### ISSUE THREAD

**Issue by seungyongshim** [seungyongshim/Work#2]
- https://devblogs.microsoft.com/premier-developer/mixing-windows-and-linux-containers-with-docker-compose/

**Comment by seungyongshim** [comment]
## docker-compose.yml
```yaml
version: '2.4'

services: 
  gitlab-runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    user: root
    privileged: true
    volumes:
      - './config.toml:/etc/gitlab-runner/config.toml'
      - '/var/run/docker.sock:/var/run/docker.sock'
  gitlab-runner-windows:
    container_name: gitlab-runner-windows
    platform: windows
    image: 'gitlab/gitlab-runner:latest'

volumes: 
  gitlab-runner-cache:
```
